controller:
#  # Activate after successful cert-manager installation
#  extraArgs:
#    default-ssl-certificate: ingress-nginx/workshop-tls-cert

  # deploy an ingress controller pod on every node
  kind: DaemonSet

  # ensure requests can only be answered by local target pods
  service:
    externalTrafficPolicy: Local

  replicaCount: 3
  minAvailable: 1

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

  # hpa only makes sense with kind Deployment
  # kind DaemonSet disables hpa automatically
  autoscaling:
    enabled: false
    minReplicas: 3
    maxReplicas: 6
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 50

  metrics:
    enabled: true

    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"

defaultBackend:
  enabled: true
