apiVersion: v1
kind: Service
metadata:
  name: echo-green
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      name: http
      targetPort: 8080
  selector:
    app: echo
    version: green
