apiVersion: v1
kind: Pod
metadata:
  name: sidecar-container-demo
  labels:
    app: sidecar-container-demo
spec:
  containers:
  - image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) 'Hi I am from Sidecar container <br>' >> /var/log/index.html; sleep 5;done"]
    name: sidecar-container
    resources: {}
    volumeMounts:
    - name: var-logs
      mountPath: /var/log
  - image: nginx
    name: main-container
    resources: {}
    ports:
      - containerPort: 80
    volumeMounts:
    - name: var-logs
      mountPath: /usr/share/nginx/html
  dnsPolicy: Default
  # create a special type of volume: emptydir
  # containers in the same pod share storage
  # bot containers mount the volume but under different mount paths
    volumes:
  - name: var-logs
    emptyDir: {}
